name: Run it on action

on:
  push:
    branches:
      - master

jobs:
    run-it:
        runs-on: ubuntu-latest
        name: Run it on action
        steps:
            - name: Checkout master
              uses: actions/checkout@master
            - name: Php env
              uses: franzliedke/gh-action-php@master
            - name: Run
              run: |
                php7.1 php -v
